### ISSUE TITLE
Can these Character Controllers and Working Combat Examples for Godot 4 help?

### ISSUE THREAD

**Issue by WithinAmesia** [don-tnowe/godot-wyvernquest-rpg#2]
Can these working combat examples help boost the combat prototype development perhaps?

https://github.com/WithinAmnesia/ARPG/discussions/4#discussioncomment-7051445 + https://github.com/WithinAmnesia/ARPG/discussions/4#discussioncomment-7149307
These are my character controllers but I held off on combat for I wanted to try and help develop an expanded combat system. There are animations but the scripting is not made yet complete for combat. Yet there are examples of possibly already made combat systems that maybe boost the first prototypes like reverse engineer?

https://github.com/WithinAmnesia/ARPG/discussions/9 
"https://github.com/Boyquotes/godot-arpg
https://github.com/aguoxing/godot4-demos/tree/main/2d/godot-arpg
MIT License forever free for both. I went through 52 'godot arpg' repository projects from 2022 to 2023 (current date 8th / 12 (December) / 2023) on github to find this and out out of 52 only 2 maybe 3 worked that had combat for Godot 4; that's less than ~5% success rate or less than one in 20 projects had working arpg combat and this was the best one of the bunch I found so far searching 'godot arpg'. I think this can help other projects for combat?"

**Comment by don-tnowe** [comment]
the wyvernshield example already has combat. sorta. am i missing something?

**Comment by WithinAmesia** [comment]
Perhaps a little example with Wyvern Quest RPG where maybe its not complete but it has a start where features get added over time? As like WASD hero controls and animations (the first link has a CC0 knight with all the moving and combat animations already rigged for Godot 4 I made. Perhaps some basic enemies like skeletons, bats and bandits / casters. Also like health bars basic deaths for enemy and player maybe 2 areas or as an outside area and an interior building / dungeon room with a chest / loot with Wyvern Inventory. For helping show case like a little demo to show off how great everything is and a feel of the game work so far; as in whats working and to help tinker with and test implementing features as time goes on?

The CC0 knight has a CC0 tileset that's like Diablo with grass and skeletons and dungeon elements too for easy prototyping https://github.com/WithinAmnesia/ARPG/tree/main/C.C.0.%20Assets%20Archive/Art/FoozleCC/Lucifer .

Perhaps its more fun to work on like having a little demo too? It might make it more fun to add features with a working little demo instead of like trying to do everything all at once? Anything to help, do you have anything I can do to help?

**Comment by don-tnowe** [comment]
Look, it appears to me that you just want me to grab these assets and mishmash them to make your game for you. But these already seem to be templates, you can just use them, or even study the code and integrate them into this example?

Wyvernquest has an ability system, half-baked, but you can add more parameters to abilities, and the health system only needs a variable to actually store the health - damage detection and calculation is already here. All this time asking me to make a game to be used for free with a "to the moon, good job keep it up baybeeeeee" attitude, spamming reactions and hoarding assets (*your repository has **no** code*), you could just be learning how to program by studying how these templates work. Go on, [Wyvernquest accepts pull requests](https://github.com/don-tnowe/godot-wyvernquest-rpg/pulls)!

You will help even more by actually trying to make a game with my addons, so that I can improve their usability and flexibility - open issues on their respective repositories if you found some feature lackluster or unintuitive to use, or found a bug, or need a feature related to working with it! Something to help the people that don't need all of them (*Wyvernshield, in fact, has **zero** issues on GitHub! Nobody cares*). Please make sure to make it related to that addon, though.

I don't have enough time to study, work, support my existing projects that people actually use, AND make a game for someone for nothing in return.

**Comment by WithinAmesia** [comment]
I'm sorry you are having a tough time right now I'm not trying to make things any harder or worse I want to help.

So I suppose you could be helped if I smashed together a rough prototype of what I shared combined with Wyvernshield even if it was not very good coding on my end it could still help you improve things and let you have a better work load and less stress I think? I am not very good at coding on the fly but I can code decently enough when I really need to. For example I coded the character example with a lot of tutorials and trial and error. I just don't feel my coding is good enough on the fly making completely new things I don't want to give people bugs and problems if I can; I want all my sharable stuff to work so people can enjoy it. I have some rough prototypes but I don't share them because I don't feel they would help much because I just break things adding stuff and bug fix until its stable and easy to enjoy. I know you are way better at coding than myself so I didn't want to give you broken messes to look at. So yeah I don't have a lot of code to share for I want to give good things to people not my broken buggy messes than only work after like round 20 of bug fixing but I have some that works even if its just complied tutorials it at least works to help I think.

I guess the issue is not like coding but like stress and over burden and not enough time to find enough healthy down time to recuperate it sounds like possibly. I get that too like being way over stressed I am sorry for stressing you out; I'm not trying to look fake like I try to help cheer people up and I am sorry if I am not good at that but I do try to help even if I am bad at it. I'd rather be bad at helping than good at not helping because I want to help and make things better. I'll just smash some abomination together I guess with wyvernshield and those combat templates and try to polish it up enough so its not a complete mess. I will suck at this but I can do it but it will be messy most likely and not very smart in areas like ramming your face in a beehive to get honey lol. I guess you are right though like if I can help I should help even if it sucks you can probably improve my crappy work way better than I can for you are a way better coder than myself. I'll start smashing things together and breaking everything until something works well enough to share I think that should help? Anyway hang in there and things will get better and you are great. I'll help too but like except like a lot of mess and version 20 iterations to finally work smoothly but I can do it. Thank you for caring so much too I'll try to be better too.
